### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by mpbraendli** [YoannQueret/ODR-tools#1]
Salut Yoann,

est-ce que tu peux utiliser zeromq des dépôts de la jessie plutôt que de compiler toi-même ?

Je vois que tu installes libsodium-dev, donc ça fait probablement un beau mélange entre des parties installées à la main et des paquets. Je fais
apt-get -y install libzmq3-dev libzmq3
dans mon script d'installation debian.sh dans le mmbtools-aux

mpb

**Comment by YoannQueret** [comment]
Salut Matthias.

J'ai update le script install.sh en fonction de tes remarques.

Yoann
